config/routes.rb
Gminer::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:show]

  resources :datasets, :samples, :series_items, :ontologies, :ontology_terms, :results, :detections, :resource_index_annotations

  resources :platforms do
    collection do
      post :skip_annotations
    end
  end

  resources :cytoscapes do
    collection do
      post :resource_count
      post :resource_count_hash
    end

    member do
      get :resource_term_ids
      get :item_json
    end
  end

  resources :probesets do
    member do
      get :compare
    end
  end

  resources :tags do
    collection do
      post :create_for
      post :delete_for
    end

    member do
      post :delete_for
    end
  end

  resources :reports do
    collection do
      get :progress
      get :job_statistics
      get :annotation
      get :manual_annotation_terms
      get :comparison
    end
  end

  resources :jobs do
    collection do
      get :graph_status
      get :dashboard
      post :process
      post :update_job_form
    end
  end

  resources :annotations do
    collection do
      get :top_curators
      get :cloud
      get :audit
      get :item_audit
      post :mass_curate
    end

    member do
      post :predicate
      post :curate
      get :geo_item
    end
  end

  match '/help', :to => 'pages#help', :as => 'help'
  match '/rdf', :to => 'pages#rdf', :as => 'rdf'
  root :to => 'pages#home'

end

app/views/shared/_admin_box.html.haml
- if admin?
  #admin-box
    = render(:partial => "shared/tags.html.haml", :locals => {:collection => geo_item.tags, :geo_accession => geo_item.geo_accession, :top_tags => top_tags, :all_tags => all_tags}) if defined?(geo_item)
    = render(:partial => "shared/annotation_counts.html.haml", :locals => {:collection => annotation_count_array}) if defined?(annotation_count_array)

app/views/shared/_admin_nav.html.haml
.quick-nav
  .prv
    <<
    = geo_link(@prev)
  .nxt
    = geo_link(@next)
    >>

app/views/shared/_annotation.html.haml
%tr{ :class => cycle('row-odd', 'row-even') }
  %td{ :valign => "top", :width => "40%" }
    = ontology_name
  %td{ :valign => "top" }
    - if admin?
      = curate_link_list.html_safe
    - else
      = term_list.html_safe

app/views/shared/_annotation_count.html.haml
%tr
  %td
    == #{annotation_count[:name]}:
  %td
    = annotation_count[:amount]

app/views/shared/_annotation_counts.html.haml
#show
  Show counts
#annotation-count
  #hide
    X
  %br
  %table
    = render(:partial => "shared/annotation_count", :collection => collection)

app/views/shared/_cloud.html.haml
.cloud-box
  .cloud-box-title
    = title
  %br
  .cloud-box-content
    %ol.tag-cloud
      - term_cloud(terms, Constants::TAG_CLASSES) do |term, css_class|
        %li
          = link_to(term.name, ontology_term_url(term), :class => css_class)

app/views/shared/_create_popup.html.haml
#new-annotation.rounded.drop-shadow
  = simple_form_for(@new_annotation) do |f|
    = f.input :ncbo_term_id, :input_html => { :class => "bp_form_complete-1150-uri" }
    = f.input :ncbo_id, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :field_name, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :from, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :to, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :created_by_id, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :curated_by_id, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :verified, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :status, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :geo_accession, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.input :description, :as => :hidden, :wrapper_html => { :style => "display:none;" }
    = f.submit(t('label.save'))
    = f.submit(t('label.cancel'), :class => "cancel", :id => "annotation_cancel")
  #annotation-result

%ul#annotation-menu.contextMenu
  - @ontologies.each do |ontology|
    %li{:class => "#{ontology.ncbo_id} separator"}
      %a{:href => "##{ontology.ncbo_id}"}
        = ontology.name

app/views/shared/_curator_table.html.haml
%table.curator-table
  %thead
    %tr.row-header
      %td{:colspan => 2}
        = title
  %tbody
    = render(:partial => "shared/curated_annotation.html.haml", :collection => items)

app/views/shared/_field.html.haml
- if !field[:value].blank?
  %tr
    %td{ :valign => "top" }
      = field[:name].humanize
    %td
      %span{ :id => field[:name] }
        = field[:value]
      .annotation-table(id="table-#{field[:name]}")
        = annotations_for(item, field[:name])

app/views/shared/_footer.html.haml
.grid-container.footer
  .grid_24
    GMiner is developed through a
    = link_to("collaboration", "http://twigger.hmgc.mcw.edu/index.php/current-grants/ncbo/", :class => 'white', :target => "_blank")
    between the
    = link_to("Twigger Lab", "http://twigger.hmgc.mcw.edu/", :class => 'white', :target => "_blank")
    at the Medical College of Wisconsin and the
    = link_to("National Center for Biomedical Ontology", "http://bioontology.org/", :class => 'white', :target => "_blank")

app/views/shared/_header.html.haml
.grid-container.header.rounded
  .grid_24
    = link_to(image_tag('layout/logo.png', :class => "gminer-logo", :alt => "GMiner"), root_url)
    = link_to(image_tag('layout/mcw_logo.gif', :class => "mcw-logo", :alt => "Medical College of Wisconsin"), "http://mcw.edu/", :target => "_blank")
    = link_to(image_tag('layout/ncbo_logo.gif', :class => "ncbo-logo", :alt => "National Center for Biomedical Ontology"), "http://bioontology.org/", :target => "_blank")
    = render(:partial => "shared/user.html.haml")
    #help
      = link_to('Help', help_url)
.clear

app/views/shared/_top_tag.html.haml
%li
  %a.add-tag{:tag_name => top_tag.name, :title => top_tag.description}
    = top_tag.name

app/views/shared/_tracking.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-111']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

app/views/shared/_user.html.haml
#user
  = signin_signout