config/routes.rb
Gminer::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:show]

  resources :datasets, :samples, :series_items, :ontologies, :ontology_terms, :results, :detections, :resource_index_annotations

  resources :platforms do
    collection do
      post :skip_annotations
    end
  end

  resources :cytoscapes do
    collection do
      post :resource_count
      post :resource_count_hash
    end

    member do
      get :resource_term_ids
      get :item_json
    end
  end

  resources :probesets do
    member do
      get :compare
    end
  end

  resources :tags do
    collection do
      post :create_for
      post :delete_for
    end

    member do
      post :delete_for
    end
  end

  resources :reports do
    collection do
      get :progress
      get :job_statistics
      get :annotation
      get :manual_annotation_terms
      get :comparison
    end
  end

  resources :jobs do
    collection do
      get :graph_status
      get :dashboard
      post :process
      post :update_job_form
    end
  end

  resources :annotations do
    collection do
      get :top_curators
      get :cloud
      get :audit
      get :item_audit
      post :mass_curate
    end

    member do
      post :predicate
      post :curate
      get :geo_item
    end
  end

  match '/help', :to => 'pages#help', :as => 'help'
  match '/rdf', :to => 'pages#rdf', :as => 'rdf'
  root :to => 'pages#home'

end

app/models/ontology.rb
class Ontology < ActiveRecord::Base
  include Utilities
  extend Utilities::ClassMethods

  has_many :ontology_terms, :dependent => :delete_all, :order => "annotations_count DESC, name"
  has_many :annotations, :dependent => :delete_all

  validates_presence_of :name
  validates_uniqueness_of :name

  class << self
    def page(conditions, page=1, size=Constants::PER_PAGE)
      paginate(:order => :name,
               :conditions => conditions,
               :page => page,
               :per_page => size
               )
    end

    def which_have_annotations
      Ontology.all(:order => :name).select { |ontology| ontology if ontology.annotations.size > 0 }
    end

    def insert_terms(file, ncbo_id)
      ontology = Ontology.first(:conditions => {:ncbo_id => ncbo_id})

      term_regex = /^\[Term\]/
      id_regex = /^id: (.+)$/
      name_regex = /^name: (.+)$/
      obsolete_regex = /^is_obsolete: (.+)$/
      in_term_flag = false
      obsolete_flag = false

      File.open(file, "rb", :encoding => 'ISO-8859-1').each do |line|

        # check if we've got a term header, and set true if we do
        if result = term_regex.match(line)
          in_term_flag = true
          @ontology_term = OntologyTerm.new(:ncbo_id => ncbo_id, :ontology_id => ontology.id)
          next
        end

        # if we're not in a term, get the next line
        if !in_term_flag
          next
        end

        # we need to save the ontology
        if in_term_flag && line.blank?
          if !obsolete_flag
            @ontology_term.save
            puts "TERM: #{@ontology_term.term_id}  #{@ontology_term.name}"
          end
          in_term_flag = false
          obsolete_flag = false
        end

        # we need to match the id
        if result = id_regex.match(line)
          term_match = result[1]
          term_id = "#{ncbo_id}|#{term_match}"
          # if we've already got that id, skip it, and move out of being in the term
          if !OntologyTerm.first(:conditions => {:term_id => term_id })
            @ontology_term.term_id = term_id
          else
            in_term_flag = false
            next
          end
        end

        # get the name of the term, save it, and move out of being in the term
        if result = name_regex.match(line)
          name_match = result[1]
          @ontology_term.name = name_match
        end

        # check if there is an obsolete line, which means we don't save it
        if result = obsolete_regex.match(line)
          if result[1] == "true"
            obsolete_flag = true
          end
        end

      end
    end
  end # of self

  def update_data
    self.current_ncbo_id, self.name, self.version = NCBOAnnotatorService.current_ncbo_id(self.ncbo_id)
    save!
  end

end

app/controllers/ontologies_controller.rb
class OntologiesController < ApplicationController

  before_filter :check_cancel, :only => [:create, :update]
  before_filter :admin_required, :only => [:new, :edit, :create, :update]

  def index
    @q = params[:query]
    page = (params[:page].to_i > 0) ? params[:page] : 1

    q_front = "#{@q}%"
    q_both = "%#{@q}%"

    cstring = "name LIKE ?"
    conditions = [cstring, q_front]

    find_ontologies(conditions, page)
    #if we have a page > the last one, redo the query turning the page into the last one
    find_ontologies(conditions, @ontologies.total_pages) if params[:page].to_i > @ontologies.total_pages

    respond_to do |format|
      format.html {}
      format.js  {
          render(:partial => "ontologies_list")
        }
    end
  end

  def new
    @ontology = Ontology.new
  end

  def create
    @ontology = Ontology.new(params[:ontology])
    if @ontology.save
      flash[:notice] = "Ontology has been created."
      redirect_to(ontologies_url)
    else
      render(:action => :new)
    end
  end

  def edit
    @ontology = Ontology.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      flash[:warning] = "That ontology does not exist."
      redirect_to(ontologies_url)
  end

  def update
    @ontology = Ontology.find(params[:id])

    if @ontology.update_attributes(params[:ontology])
      flash[:notice] = 'Ontology was successfully updated.'
      redirect_to(ontologies_url)
    else
      render(:action => :edit)
    end
  end

  def show
    @ontology = Ontology.find(params[:id])

    page = (params[:page].to_i > 0) ? params[:page].to_i : 1

    @q = params[:query]
    q_front = "#{@q}%"

    cstring = "ontology_id = ? AND name LIKE ?"
    conditions = [cstring, @ontology.id, q_front]

    find_ontology_terms(conditions, page)
    #if we have a page > the last one, redo the query turning the page into the last one
    find_ontology_terms(conditions, @ontology_terms.total_pages) if params[:page].to_i > @ontology_terms.total_pages

    respond_to do |format|
      format.html {}
      format.js  {
          render(:partial => "ontology_term_list.html.haml")
        }
    end

    rescue ActiveRecord::RecordNotFound
      flash[:warning] = "That ontology does not exist."
      redirect_to(ontologies_url)
  end

  protected
    def find_ontologies(conditions, page)
      @ontologies = Ontology.page(conditions, page, Constants::PER_PAGE)
    end

    def find_ontology_terms(conditions, page)
      @ontology_terms = OntologyTerm.page_for_ontology(conditions, page, Constants::PER_PAGE)
    end

    def check_cancel
      redirect_to(ontologies_url) and return if (params[:commit] == t('label.cancel'))
    end

end

app/views/ontologies/_form.html.haml
= form.input :name
= form.input :current_ncbo_id, :label => "Current NCBO ID"
= form.input :ncbo_id, :label => "Virtual NCBO ID"
= form.input :version
= form.input :stopwords

app/views/ontologies/_ontologies_list.html.haml
%br
- if @ontologies.size == 0
  %p
    No ontologies found...
- else
  %p
    = found_count("ontologies", @ontologies)
  %p
    = render(:partial => "shared/pagination.html.haml", :locals => {:items => @ontologies})
  %br
  %table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
    %thead
      %tr.row-header
        %td{:width => "30%"}
          Name
        %td{:width => "10%"}
          Version
        - if admin?
          %td{:width => "50%"}
            Stopwords
          %td{:width => "10%"}
            Action
    %tbody#staffTable
      = render(:partial => "ontology.html.haml", :collection => @ontologies)

app/views/ontologies/_ontology.html.haml
%tr{:class => "#{cycle('row-odd', 'row-even')}"}
  %td{:valign => "top"}
    = link_to(highlight(ontology.name, @q), ontology_url(ontology))
  %td{:valign => "top"}
    = ontology.version
  - if admin?
    %td{:valign => "top"}
      = ontology.stopwords.split(',').join(', ')
    %td{:valign => "top"}
      = link_to(t('link.edit'), edit_ontology_path(ontology))

app/views/ontologies/_ontology_term.html.haml
%tr{:class => "#{cycle('row-odd', 'row-even')}"}
  %td{:valign => "top", :width => "40%"}
    = link_to(ontology_term.name, ontology_term_url(ontology_term))
    = ncbo_ontology_link(ontology_term)
  %td{:valign => "top"}
    = has_annotations(ontology_term.annotations_count)
  - if admin?
    %td{:valign => "top"}
      = annotation_percentage(ontology_term.annotations_count, ontology_term.valid_annotation_percentage)
    %td{:valign => "top"}
      = annotation_percentage(ontology_term.annotations_count, ontology_term.audited_annotation_percentage)
      - if (ontology_term.annotations_count > 0) && (ontology_term.audited_annotation_percentage < 100)
        %br
        = link_to("Audit", audit_annotations_url(:query => ontology_term.name, :status => "Unaudited", :ddown => ontology_term.ontology.ncbo_id))

app/views/ontologies/_ontology_term_list.html.haml
%br
- if @ontology_terms.size == 0
  %p
    No ontology terms found...
- else
  %p
    = found_count("ontology term", @ontology_terms)
  %p
    = render(:partial => "shared/pagination.html.haml", :locals => {:items => @ontology_terms, :limit => false})
  %br
  %table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
    %thead
      %tr.row-header
        %td{:width => "40%"}
          Ontology term
        %td{:width => "20%"}
          Annotation count
        - if admin?
          %td{:width => "20%"}
            Valid
          %td{:width => "20%"}
            Audited
    %tbody
      = render(:partial => "ontology_term.html.haml", :collection => @ontology_terms)

app/views/ontologies/edit.html.haml
- title t('.title')
= page_title(t('.title'))
= simple_form_for(@ontology) do |f|
  = error_messages_for(@ontology)
  = render(:partial => "ontologies/form", :object => f)
  = f.submit(t('label.update'))
  = f.submit(t('label.cancel'))

app/views/ontologies/index.html.haml
= page_title("Ontologies")
- if admin?
  %br
  = link_to("Create ontology", new_ontology_path)
  %br
%p
  %form{:name => "sform", :action => "", :style => "display:inline"}
    %label
      Filter on name:
    = text_field_tag(:query, params['query'], :autocomplete => 'off')
.dataTable
  = render(:partial => "ontologies_list.html.haml")

app/views/ontologies/new.html.haml
- title t('.title')
= page_title(t('.title'))
%br
= simple_form_for(@ontology) do |f|
  = error_messages_for(@ontology)
  = render(:partial => "ontologies/form", :object => f)
  = f.submit(t('label.save'))
  = f.submit(t('label.cancel'))

app/views/ontologies/show.html.haml
= page_title("Ontology: #{@ontology.name}")
%br
= link_to('Back', ontologies_url)
%p
  %form{:name => "sform", :action => "", :style => "display:inline"}
    %label
      Filter on name:
    = text_field_tag(:query, params['query'], :autocomplete => 'off')
.dataTable
  = render(:partial => "ontology_term_list.html.haml")