config/routes.rb
Gminer::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:show]

  resources :datasets, :samples, :series_items, :ontologies, :ontology_terms, :results, :detections, :resource_index_annotations

  resources :platforms do
    collection do
      post :skip_annotations
    end
  end

  resources :cytoscapes do
    collection do
      post :resource_count
      post :resource_count_hash
    end

    member do
      get :resource_term_ids
      get :item_json
    end
  end

  resources :probesets do
    member do
      get :compare
    end
  end

  resources :tags do
    collection do
      post :create_for
      post :delete_for
    end

    member do
      post :delete_for
    end
  end

  resources :reports do
    collection do
      get :progress
      get :job_statistics
      get :annotation
      get :manual_annotation_terms
      get :comparison
    end
  end

  resources :jobs do
    collection do
      get :graph_status
      get :dashboard
      post :process
      post :update_job_form
    end
  end

  resources :annotations do
    collection do
      get :top_curators
      get :cloud
      get :audit
      get :item_audit
      post :mass_curate
    end

    member do
      post :predicate
      post :curate
      get :geo_item
    end
  end

  match '/help', :to => 'pages#help', :as => 'help'
  match '/rdf', :to => 'pages#rdf', :as => 'rdf'
  root :to => 'pages#home'

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  attr_accessible :description

  class << self
    def page(conditions, page=1, size=Constants::PER_PAGE)
      paginate(:order => :name,
               :conditions => conditions,
               :page => page,
               :per_page => size
               )
    end

    def top_tags(tags=[], limit=10)
      tag_list = "'"
      tag_list << tags.join("','")
      tag_list << "'"

      find(:all,
          :select => 'tags.id, name, description, count(tag_id) AS count',
          :conditions => "name NOT IN (#{tag_list})",
          :group => :id,
          :limit => limit,
          :order => 'count DESC, name',
          :joins => 'LEFT JOIN taggings ON taggings.tag_id = tags.id')

    end

    def all_tags(tags=[])
      tag_list = "'"
      tag_list << tags.join("','")
      tag_list << "'"

      tags = find(:all,
          :select => :name,
          :conditions => "name NOT IN (#{tag_list})",
          :order => :name)
    end


    def process_tagging(action, geo_accession, tag_list)
      item = Tag.load_item(geo_accession)
      if (item.is_a?(SeriesItem))
        process_children(action, item, tag_list)
        process_item(action, item, tag_list)
      else
        process_item(action, item, tag_list)
      end
      item
    end

    def process_children(action, item, tag_list)
      item.samples.each do |sample|
        process_item(action, sample, tag_list)
      end
    end

    def process_item(action, item, tag_list)
      if (action == "create")
        item.tag_list.add(tag_list, :parse => true)
      elsif (action == "delete")
        item.tag_list.remove(tag_list, :parse => true)
      end
      item.save
      item.reload
    end

    def load_item(key)
      case key
        when /^GSM/
          m = Sample
        when /^GSE/
          m = SeriesItem
        when /^GPL/
          m = Gminer::Platform
        when /^GDS/
          m = Dataset
      end
      m.first(:select => '*', :conditions => {:geo_accession => key})
    end

  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_filter :check_cancel, :only => [:create, :update]
  before_filter :admin_required

  def index
    @q = params[:query]
    page = (params[:page].to_i > 0) ? params[:page] : 1

    q_front = "#{@q}%"

    cstring = "name LIKE ?"
    conditions = [cstring, q_front]

    find_tags(conditions, page)
    #if we have a page > the last one, redo the query turning the page into the last one
    find_tags(conditions, @tags.total_pages) if params[:page].to_i > @tags.total_pages

    respond_to do |format|
      format.html {
        }
      format.js  {
          render(:partial => "tags_list.html.haml")
        }
    end
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(params[:tag])
    if @tag.save
      flash[:notice] = "Tag has been created."
      redirect_to(tags_url)
    else
      render(:action => :new)
    end
  end

  def create_for
    @item = Tag.process_tagging('create', params[:geo_accession], params[:tag_list])
    @top_tags = Tag.top_tags(@item.tag_list)
    @all_tags = Tag.all_tags(@item.tag_list).map(&:name)
    render(:action => "update.js.haml")
  end

  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html
    end

    rescue ActiveRecord::RecordNotFound
      flash[:warning] = "That tag does not exist."
      redirect_to(tags_url)
  end

  def edit
    @tag = Tag.find(params[:id])

    rescue ActiveRecord::RecordNotFound
      flash[:warning] = "That tag does not exist."
      redirect_to(tags_url)
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update_attributes(params[:tag])
      flash[:notice] = 'Tag was successfully updated.'
      redirect_to(tags_url)
    else
      render(:action => :edit)
    end
  end

  def destroy
  end

  def delete_for
    @item = Tag.process_tagging('delete', params[:geo_accession], params[:tag_list])
    @top_tags = Tag.top_tags(@item.tag_list)
    @all_tags = Tag.all_tags(@item.tag_list).map(&:name)
    render(:action => "update.js.haml")
  end


  protected

    def find_tags(conditions, page)
      @tags = Tag.page(conditions, page, Constants::PER_PAGE)
    end

    def check_cancel
      redirect_to(tags_url) and return if (params[:commit] == t('label.cancel'))
    end

end

app/helpers/tags_helper.rb
module TagsHelper

  def tagged_items(tag)
    tag.taggings.inject([]) do |array, tagging|
      array << geo_link(tagging.taggable.geo_accession)
      array
    end.join(", ")
  end

end

app/views/tags/_form.html.haml
= form.input :name
= form.input :description

app/views/tags/_tag.html.haml
%tr{:class => "#{cycle('row-odd', 'row-even')}"}
  %td{:valign => "top"}
    = link_to(tag.name, tag_url(tag))
  %td{:valign => "top"}
    = tag.description
  %td{:valign => "top"}
    = tag.taggings.size
  %td{:valign => "top"}
    = link_to("Edit", edit_tag_url(tag))

app/views/tags/_tags_list.html.haml
%br
- if @tags.size == 0
  %p
    No tags found...
- else
  %p
    = found_count("tags", @tags)
  %p
    = render(:partial => "shared/pagination", :locals => {:items => @tags})
  %br
  %table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
    %thead
      %tr.row-header
        %td{:width => "20%"}
          Name
        %td{:width => "50%"}
          Description
        %td{:width => "10%"}
          Count
        %td{:width => "10%"}
          Actions
    %tbody#staffTable
      = render(:partial => "tag", :collection => @tags)

app/views/tags/edit.html.haml
- title t('.title')
= page_title(t('.title'))
%br
= simple_form_for(@tag) do |f|
  = error_messages_for(@tag)
  = render(:partial => "tags/form.html.haml", :object => f)
  = f.submit(t('label.save'))
  = f.submit(t('label.cancel'))

app/views/tags/index.html.haml
- title t(".title")
= page_title(t('.title'))
%br
= link_to(t('.new_link'), new_tag_url)
%p
  %form{:name => "sform", :action => "", :style => "display:inline"}
    %label
      Filter on name:
    = text_field_tag(:query, params['query'], :autocomplete => 'off')
.dataTable
  = render(:partial => "tags_list.html.haml")

app/views/tags/new.html.haml
- title t('.title')
= page_title(t('.title'))
%br
= simple_form_for(@tag) do |f|
  = error_messages_for(@tag)
  = render(:partial => "tags/form.html.haml", :object => f)
  = f.submit(t('label.save'))
  = f.submit(t('label.cancel'))

app/views/tags/show.html.haml
- title t('.title')
= page_title(t('.title'))
%p
  = link_to("back", tags_url)
%p
  %strong
    Name:
  = @tag
%strong
  Tagged items
%p
  = html_safe(tagged_items(@tag))

app/views/tags/update.js.haml
== $("#active.tag-list").html("#{escape_javascript(render(:partial => "shared/tag.html.haml", :collection => @item.tags))}");
== $("#available.tag-list").html("#{escape_javascript(render(:partial => "shared/top_tag.html.haml", :collection => @top_tags))}");
== var tags = #{raw(@all_tags)};
== $('#tag_list').autocompleteArray(tags, { autoFill:true });