config/routes.rb
Gminer::Application.routes.draw do

  devise_for :users

  resources :users, :only => [:show]

  resources :datasets, :samples, :series_items, :ontologies, :ontology_terms, :results, :detections, :resource_index_annotations

  resources :platforms do
    collection do
      post :skip_annotations
    end
  end

  resources :cytoscapes do
    collection do
      post :resource_count
      post :resource_count_hash
    end

    member do
      get :resource_term_ids
      get :item_json
    end
  end

  resources :probesets do
    member do
      get :compare
    end
  end

  resources :tags do
    collection do
      post :create_for
      post :delete_for
    end

    member do
      post :delete_for
    end
  end

  resources :reports do
    collection do
      get :progress
      get :job_statistics
      get :annotation
      get :manual_annotation_terms
      get :comparison
    end
  end

  resources :jobs do
    collection do
      get :graph_status
      get :dashboard
      post :process
      post :update_job_form
    end
  end

  resources :annotations do
    collection do
      get :top_curators
      get :cloud
      get :audit
      get :item_audit
      post :mass_curate
    end

    member do
      post :predicate
      post :curate
      get :geo_item
    end
  end

  match '/help', :to => 'pages#help', :as => 'help'
  match '/rdf', :to => 'pages#rdf', :as => 'rdf'
  root :to => 'pages#home'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  before_filter :admin_required

  def index
  end

  def progress
    @result_hash = ProgressReport.results
  end

  def comparison
    set_date_dropdown
    @result_hash = ComparisonReport.results(@comparison_date)

    @comparison_field_name_hash = Comparison.get_field_name_hash(@comparison_date)

    respond_to do |format|
      format.html { }
      format.js  {
          render(:partial => "reports/comparison_report.html.haml")
        }
      format.xml  {}
      format.csv  {}
    end
  end

  def annotation
    set_ontology_dropdown
    set_geotype_dropdown

    report = AnnotationReport.new
    report.setup(@ontology, @geotype)

    @fields, @result_hash = report.results

    respond_to do |format|
      format.html { }
      format.js  {
          render(:partial => "reports/annotation_report.html.haml")
        }
    end
  end

  def manual_annotation_terms

    respond_to do |format|
      format.html { }
      format.csv  {
        @terms = AnnotationReport.manual_terms
        csv_string = CSV.generate do |csv|
          # header row
          csv << ["term_name", "term_id", "term_text", "ncbo_id", "geo_accession", "field_name", "from", "to"]
          @terms.each do |term|
            csv << [term[:term_name], term[:term_id], term[:term_text], term[:ncbo_id], term[:geo_accession], term[:field_name], term[:from], term[:to]]
          end
        end
        filename = "manual_annotation_terms"
        # send it to the browsah
        send_data(csv_string.force_encoding('UTF-8'), :type => 'text/csv; charset=UTF-8; header=present', :disposition => "attachment; filename=#{filename}.csv")
      }
    end
  end

  def job_statistics
    @results_hash = Job.get_statistics
    respond_to do |format|
      format.html { }
      format.csv  {
        csv_string = CSV.generate do |csv|
          # header row
          csv << ["detail", "count", "NCBO ave time", "ave time", "min time", "max time"]
          @results_hash.keys.sort.each do |geo_item|
            csv << [geo_item, @results_hash[geo_item][:count], @results_hash[geo_item][:ncbo_average_time], @results_hash[geo_item][:average_time], @results_hash[geo_item][:min_time]]
            if @results_hash[geo_item][:field_names].any?
              @results_hash[geo_item][:field_names].keys.sort.each do |field_name|
                csv << ["#{geo_item}:#{field_name}", @results_hash[geo_item][:field_names][field_name][:count], @results_hash[geo_item][:field_names][field_name][:ncbo_average_time], @results_hash[geo_item][:field_names][field_name][:average_time], @results_hash[geo_item][:field_names][field_name][:min_time], @results_hash[geo_item][:field_names][field_name][:max_time]]
                if @results_hash[geo_item][:field_names][field_name][:ontology_ids].any?
                  @results_hash[geo_item][:field_names][field_name][:ontology_ids].keys.sort.each do |ontology|
                    csv << ["#{geo_item}:#{field_name}:#{@results_hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:name]}", @results_hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:count], @results_hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:ncbo_average_time], @results_hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:average_time], @results_hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:min_time], @results_hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:max_time]]
                  end
                end
              end
            end
          end
        end
        filename = "job_statistics_#{Time.now.to_s(:file)}"
        # send it to the browsah
        send_data(csv_string.force_encoding('UTF-8'), :type => 'text/csv; charset=UTF-8; header=present', :disposition => "attachment; filename=#{filename}.csv")
      }
    end
  end


  protected
    def set_ontology_dropdown
      @ontology = params[:ddown] ? params[:ddown] : Annotation.first ? Annotation.first.ncbo_id : ""
    end

    def set_geotype_dropdown
      @geotype = params[:geotype] ? params[:geotype] : "Platform"
    end

    def set_date_dropdown
      @comparison_date = params[:ddown] ? params[:ddown] : Comparison.get_newest_date
    end

end

app/helpers/reports_helper.rb
module ReportsHelper

  def field_name_display(field_name, array)
    if array.include?(field_name)
      "automatic"
    else
      "manual"
    end
  end

  def change_formatted(current, previous, type, manual=false)
    change = ('%.2f' % change_percentage(current, previous, manual))

    if type == "increase"
      positive = "red"
      negative = "green"
    else
      positive = "green"
      negative = "red"
    end

    if change.to_f > 0
      "<span class='change #{positive}'>#{change}%</span>".html_safe
    elsif change.to_f < 0
      "<span class='change #{negative}'>#{change}%</span>".html_safe
    elsif previous.to_f > 0
      "0.0%"
    else
      ""
    end
  end

  def change_percentage(current, previous, manual=false)
    cf = current.to_f
    pf = previous.to_f
    return 0 if (cf == 0 || pf == 0)
    percent_change = manual ? (cf/pf)*100 : ((cf-pf)/cf)*100
  end

  def comparison_date_dropdown(current)
    select_tag(:ddown, options_from_collection_for_select(Comparison.get_all_dates, :archived_at, :archived_at, current))
  end

end

app/views/reports/_annotation_field.html.haml
%tr
  %td(valign='top')
    = annotation_field
  %td(valign='top' width="30%")
    = result_hash[annotation_field][:valid].join(", ")
  %td(valign='top' width="30%")
    = result_hash[annotation_field][:invalid].join(", ")
  %td(valign='top' width="30%")
    = result_hash[annotation_field][:unaudited].join(", ")

app/views/reports/_comparison_graph.html.haml
%div.pie-chart{:id => "chart_#{comparison_graph}"}

app/views/reports/_field_name.csv.haml
==#{comparison_date}, #{ontology_name}, #{field_name}, #{hash[field_name]['seen_valid']}, #{hash[field_name]['valid_previous']}, #{change_percentage(hash[field_name]['seen_valid'], hash[field_name]['valid_previous'])}, #{hash[field_name]['seen_invalid']}, #{hash[field_name]['invalid_previous']}, #{change_percentage(hash[field_name]['seen_invalid'], hash[field_name]['invalid_previous'])}, #{hash[field_name]['seen_unaudited']}, #{hash[field_name]['unaudited_previous']}, #{change_percentage(hash[field_name]['seen_unaudited'], hash[field_name]['unaudited_previous'])}, #{hash[field_name]['seen_manual']}, #{hash[field_name]['manual_previous']}, #{change_percentage(hash[field_name]['seen_manual'], hash[field_name]['manual_previous'])}, #{hash[field_name]['not_seen']}, #{hash[field_name]['current_total']}, #{hash[field_name]['previous_total']}, #{change_percentage(hash[field_name]['current_total'], hash[field_name]['previous_total'])}

app/views/reports/_field_name.xml.haml
%name= field_name
%seenvalid
  %current= hash[field_name]['seen_valid']
  %previous= hash[field_name]['valid_previous']
  %change= change_percentage(hash[field_name]['seen_valid'], hash[field_name]['valid_previous'])
%seeninvalid
  %current= hash[field_name]['seen_invalid']
  %previous= hash[field_name]['invalid_previous']
  %change= change_percentage(hash[field_name]['seen_invalid'], hash[field_name]['invalid_previous'])
%seenunaudited
  %current= hash[field_name]['seen_unaudited']
  %previous= hash[field_name]['unaudited_previous']
  %change= change_percentage(hash[field_name]['seen_unaudited'], hash[field_name]['unaudited_previous'])
%seenmanual
  %current= hash[field_name]['seen_manual']
  %previous= hash[field_name]['manual_previous']
  %change= change_percentage(hash[field_name]['seen_manual'], hash[field_name]['manual_previous'])
%notseen
  %current= hash[field_name]['not_seen']
%total
  %current= hash[field_name]['current_total']
  %previous= hash[field_name]['previous_total']
  %change= change_percentage(hash[field_name]['current_total'], hash[field_name]['previous_total'])

app/views/reports/_geo_item.html.haml
%tr
  %td
    = geo_item
  %td
    = hash[geo_item][:count]
  %td
    = hash[geo_item][:ncbo_average_time]
  %td
    = hash[geo_item][:average_time]
  %td
    = hash[geo_item][:min_time]
  %td
    = hash[geo_item][:max_time]
- if hash[geo_item][:field_names].any?
  = render(:partial => "field_name.html.haml", :collection => hash[geo_item][:field_names].keys.sort, :locals => {:geo_item => geo_item, :hash => hash})

app/views/reports/_ontology.html.haml
%tr
  %td
    == #{geo_item} : #{field_name} : #{hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:name]}
  %td
    = hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:count]
  %td
    = hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:ncbo_average_time]
  %td
    = hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:average_time]
  %td
    = hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:min_time]
  %td
    = hash[geo_item][:field_names][field_name][:ontology_ids][ontology][:max_time]

app/views/reports/_ontology.xml.haml
%ontology
  %name= Constants::ONTOLOGIES[ontology][:name]
  %ncbo_ontology_id= ontology
  - if @result_hash[ontology].keys.any?
    %field_names
      = render(:partial => "reports/field_name.xml.haml", :collection => @result_hash[ontology].keys.sort, :locals => {:hash => @result_hash[ontology]})

app/views/reports/_progress_geo_type.html.haml
%tr
  %td
    = progress_geo_type
  %td
    = result_hash[progress_geo_type]['verified']
  %td
    = result_hash[progress_geo_type]['unverified']
  %td
    = result_hash[progress_geo_type]['unaudited']
  %td
    = result_hash[progress_geo_type]['manual']
  %td
    = result_hash[progress_geo_type]['total']
  %td
    = result_hash[progress_geo_type]['percent']
- if !result_hash[progress_geo_type]['chart'].blank?
  = high_pie("chart_#{progress_geo_type}", result_hash[progress_geo_type]['chart'])

app/views/reports/comparison.csv.haml
comparison_date, ontology, field_name, seen_valid_current, seen_valid_previous, seen_valid_change, seen_invalid_current, seen_invalid_previous, seen_invalid_change, seen_unaudited_current, seen_unaudited_previous, seen_unaudited_change, seen_manual_current, seen_manual_previous, seen_manual_change, not_seen, total_current, total_previous, total_change
= render(:partial => "reports/ontology.csv.haml", :collection => Constants::ONTOLOGIES.keys.sort, :locals => {:ontology_hash => @result_hash, :comparison_date => @comparison_date})

app/views/reports/comparison.html.haml
- title t(".title")
= page_title(t('.title'))
.description
  = t('.description')
%p
  %form{:name => "sform", :action => "", :style => "display:inline"}
    %label
      Filter on date:
    = comparison_date_dropdown(@comparison_date)
%br
%br
.manual
  Field has only manual annotations
.automatic
  Field has manual and automatic annotations
%br
.dataTable
  = render(:partial => "comparison_report.html.haml")

app/views/reports/comparison.xml.haml
!!! XML
%report
  %date=@comparison_date
  %ontologies
    = render(:partial => "reports/ontology.xml.haml", :collection => Constants::ONTOLOGIES.keys.sort)

app/views/reports/job_statistics.html.haml
- title t(".title")
= page_title(t('.title'))
%br
= link_to("Download csv file", job_statistics_reports_url(:format => "csv"))
%br
%br
.dataTable
%table{:width => "100%", :border => "0", :cellpadding => "0", :cellspacing => "2"}
  %tr
    %th
      Detail
    %th{:width => "10%"}
      Count
    %th{:width => "10%"}
      NCBO Ave Time
    %th{:width => "10%"}
      Ave Time
    %th{:width => "10%"}
      Min Time
    %th{:width => "10%"}
      Max Time
  = render(:partial => "geo_item.html.haml", :collection => @results_hash.keys.sort, :locals => {:hash => @results_hash} )

app/views/reports/manual_annotation_terms.html.haml
- title t(".title")
= page_title(t('.title'))
.description
  = t('.description')
%br
== This report is currently available as a 'csv' #{link_to('download', manual_annotation_terms_reports_url(:format => "csv"))}.

app/views/reports/progress.html.haml
- title t(".title")
= page_title(t('.title'))
.description
  = t('.description')
%br
.dataTable
  = render(:partial => "progress_report.html.haml")